#server:
#  address: 10.0.61.27
#  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/h2/java_testing
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
